center window if it's outside of screen
trueagi-io/Vereya pull request #12
Opened 2023-01-19 17:43 UTC by noskill

2023-01-20 07:41 UTC, DaddyWesker approved these changes

2023-01-20 07:47 UTC, CICS-Oleg approved these changes

2023-01-20 08:15 UTC, Necr0x0Der requested changes
This fix doesn't work for me. The problem arises after `resizeIfNeeded` is called in `VideoHook`, while window centering is performed before this.  I checked that if I put `resizeIfNeeded` at the beginning of post-rendering, it works well for me. But I'm not sure this is the best place to put it.
I'd also prefer to be able to move the window. When I try to do this, it returns back (this behavior was before for me and is not affected by this PR).  Having a fixed window position is inconvenient. I wonder if this behavior appears on different platforms.

2023-01-23 08:58 UTC, Necr0x0Der commented
Unfortunately, the last commit doesn't work for me - it restores the same position, which is not affected by the user's attempt to move the window.

2023-01-25 07:53 UTC, closed without merging