bad alloc fix for AgentHost
trueagi-io/Vereya pull request #21
Opened 2022-10-19 16:04 UTC by CICS-Oleg

Fix for bad alloc problem added

2022-10-20 09:12 UTC, noskill requested changes

2022-10-20 09:16 UTC, CICS-Oleg commented on Malmo/src/AgentHost.cpp
> +        {ClientPool client_pool;
There is no { in the last commit.

2022-10-26 15:52 UTC, noskill approved these changes

2022-10-28 09:09 UTC, noskill commented on Malmo/src/TimestampedVideoFrame.cpp
> +	//std::cout <<"frame constructor "<< message.data.size()<<std::endl;
```suggestion
```

2022-10-28 09:11 UTC, noskill commented on Malmo/src/TimestampedVideoFrame.cpp
> +	//std::cout<<"!!! 1"<<std::endl;
```suggestion
```

2022-10-28 09:12 UTC, noskill commented on Malmo/src/VideoServer.cpp
> +		//std::cout<<"after writer " << frame->pixels.size()<<std::endl;
```suggestion
```

2022-10-28 09:13 UTC, noskill commented on Malmo/src/TimestampedVideoFrame.cpp
> +	//std::cout<<"!!! 2"<<std::endl;
```suggestion
```

2022-10-28 09:14 UTC, noskill commented on Malmo/src/AgentHost.cpp
> +	//auto v = boost::make_shared<TimestampedVideoFrame>( *message );
```suggestion
```

2022-10-28 09:14 UTC, noskill commented on Malmo/src/AgentHost.cpp
> +
```suggestion
```

2022-10-28 09:15 UTC, noskill commented on Malmo/src/AgentHost.cpp
> +        LOGSIMPLE(LOG_FINE, "processing video message");
```suggestion
        LOGSIMPLE(LOG_FINE, "processing video message");
```

2022-10-28 09:15 UTC, noskill commented on Malmo/src/AgentHost.cpp
> +
```suggestion
```

2022-10-28 09:15 UTC, noskill commented on Malmo/src/AgentHost.cpp
> +
```suggestion
```

2022-10-28 09:16 UTC, noskill commented on Malmo/src/AgentHost.cpp
> +
```suggestion
```

2022-10-28 09:17 UTC, noskill commented on Malmo/src/AgentHost.cpp
> +
```suggestion
```

2022-10-28 09:17 UTC, noskill commented on Malmo/src/AgentHost.cpp
> +
```suggestion
```

2022-10-28 09:17 UTC, noskill commented on Malmo/src/AgentHost.cpp
> +
```suggestion
```

2022-10-28 09:18 UTC, noskill commented on Malmo/src/VideoServer.cpp
> +
```suggestion
```

2022-10-31 09:10 UTC, merged